server:
  port: 9191
spring:  application:    name: CURRENCY-EXCHANGE-API
---
#DB Configuration
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: system
    password: system
---
#Data Jpa Configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
         hibernate:
            dialect: org.hibernate.dialect.OracleDialect
---
#Logging Configuration
logging:  file:    name: Currency_Exchange_Api.log
  level:    root: info 